name: Build Next Webapp

on:
  push:
    branches: [dev]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: filecoin/filplus/filecoin-plus-webapp-next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cristi-mb/build-be@main
        id: build-be
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          ecr-repository: ${{ env.ECR_REPOSITORY }}

      - name: Show image tag
        if: steps.build-be.outcome == 'success'
        run: echo "${{ steps.build-be.outputs.image-tag }}"
